### PR TITLE
Use shared GitHub Actions

### PR DESCRIPTION
**Pull request by zmughal**
Connects with <https://github.com/PDLPorters/devops/pull/8>.

### CODE REVIEW

**Comment by zmughal** [comment]
See run at <https://github.com/zmughal/PDL-CCS/actions>.

This can also submit code coverage to <https://coveralls.io/> if you enable it.

Edit: except Devel::Cover is failing... this appears to be a bug in Devel::Cover.

**Comment by moocow-the-bovine** [comment]
hi Zaki @zmughal,

Thanks for the PR: it looks potentially very useful.  I've never used github actions (nor coveralls) before, and don't have many TUITs to dig into those right now.  I'm also a bit concerned about upstream bugs causing me unnecessary pain & anguish (a la the perl-5.30 failures in your example run).  That said, this is totally non-invasive as far as the perl+pdlpp code is concerned, so if merging it would help you & the PDL-porters (-> can you briefly sketch how/why/where that would be so?), I'm fine with merging it.

**Comment by mohawk2** [comment]
The way I think of this is that upstream bugs and/or legitimate changes of behaviour can happen, and this CI stuff can at least let us know. Sometimes this will prompt a report upstream; sometimes it will reveal an actual bug in e.g. this module which can just be fixed in a backwards-compatible way; sometimes it will require something else.  But having more information is generally better, and specifically safer, than not.

**Comment by zmughal** [comment]
To add to what @mohawk2 said, this helps everyone because when those changes
are proposed, they will automatically run against different configurations
(versions of Perl, OSes) and you can see that they pass without needing to
install them yourself.

In addition, since the set of configurations / commands used in this workflow
is also what is used to test PDL itself, it benefits from shared improvements
to the workflow without you having to do anything.

In a bit I will be working on a way to test PDL + downstream for release
candidates of PDL so that any if anything breaks, it will be detected far
before a stable release (much like how P5P tests Perl against CPAN).

In the case of the failure with Perl 5.30 here, the failure is not due to PDL,
PDL::CCS, nor the workflow, but a bug in Devel::Cover where it is not tracking
files in subdirectories properly.  This is something I will be looking into
and that is why I have this PR as a draft. I could also comment out that line
so that it does not run coverage, but I would like to keep it open as a
reminder that this needs to be fixed — if I do not get to it within a week or
so, I'll comment it out just so that the benefit of CI is there.

**Comment by mohawk2** [comment]
And speaking of downstream testing and CI, @zmughal spotted that PDL 2.073 broke this module (sorry). Fixes at #4.

**Comment by zmughal** [comment]
The Devel::Cover bug I found here has a patch, so hopefully this PR is now ready.

Patch is here <https://github.com/pjcj/Devel--Cover/compare/master...zmughal:chdir-paths> and being pulled from <https://github.com/pjcj/Devel--Cover/compare/master...PDLPorters:patches>.

**Comment by mohawk2** [comment]
Looks good to me! @moocow-the-bovine What are your thoughts?

**Comment by moocow-the-bovine** [comment]
Awesome -- thanks to you both!

**Pull request merged**
