### PR TITLE
If want $PDL::VERSION, load PDL

### PR DESCRIPTION
**Pull request by mohawk2**
If this meets your approval, please could you merge and release it?

Also, are you yet open to switching away from supporting PDLs from 5 years ago? :-)

### CODE REVIEW

**Comment by moocow-the-bovine** [comment]
@mohawk2 thanks for the PR, merged & in the process of releasing as PDL-CCS-1.23.24

> Also, are you yet open to switching away from supporting PDLs from 5 years ago? :-)

I'm willing to consider it ... but feel obliged to warn you that I'm particularly slothful at the moment Maybe a PDL from 3 years ago (2.081 ~ bookworm).

**Comment by mohawk2** [comment]
@moocow-the-bovine Thank you for the merge and release. Please be aware that the ChangeLog entry, like the commit message, refers to "1.24.24", while the version you've actually created and released is "1.23.24", which means that MetaCPAN doesn't think the changelog entry pertains to this version. That might be something to think about automating and/or having a `xt` test for.

**EDIT** our messages crossed: ~Also, what actually are your thoughts on minimum PDL version to support?~

**Comment by moocow-the-bovine** [comment]
1.24.24 - do'h! stupid typo, thanks for spotting it ... I guess I'll just bump to 1.23.25 (because  I don't want to deal with trying to to "sneaky" things with cpan).

as far as minimum version to support: typically whatever debian stable includes ... at the moment, that seems to be 2.081 ;-)

**Comment by mohawk2** [comment]
> 1.24.24 - do'h! stupid typo, thanks for spotting it ... I guess I'll just bump to 1.23.25 (because I don't want to deal with trying to to "sneaky" things with cpan).

That would be helpful for MetaCPAN users, especially if you merge the changelog entry for this one in.

> as far as minimum version to support: typically whatever debian stable includes ... at the moment, that seems to be 2.081 ;-)

Thank you, I will bear in mind and when I get to it, PR an update to zap all the things that accommodate PDLs before that ;-)

**Comment by moocow-the-bovine** [comment]
> PR an update to zap all the things that accommodate PDLs before that

that would be awesome, thank you!

**Pull request merged**
